Add CMake support
davidrmiller/biosim4 pull request #41
Opened 2021-12-12 20:57 UTC by davidrmiller

Comments are welcome.
Are any changes needed in the docker support?
Is the README.md file sufficiently clear?

2021-12-12 23:44 UTC, mathematicalmichael commented
@davidrmiller want me to check the cmake instructions shown in the readme from inside of the docker container? Otherwise I don't (off the top of my head) know of any need to change the image to continue supporting the `make` command.

Is there any particular benefit to using cmake over make if one is developing without an IDE?

2021-12-12 23:55 UTC, davidrmiller commented
@mathematicalmichael , I would love your evaluation on the impact to the docker container, thanks.

2022-01-23 09:31 UTC, apatho requested changes

2022-01-23 09:31 UTC, apatho commented on src/CMakeLists.txt
> +SET(GCC_COVERAGE_LINK_FLAGS    "-lpthread -O3 -s -lz -lgomp")
Why add the -s option? This strips out all debug information from the executable, making debugging impossible. Since I'm not really that familiar with gcc flags, I spent quite a while trying to figure out why debugging doesn't work.

2022-01-24 15:49 UTC, mathematicalmichael commented
@davidrmiller fwiw, the docker image doesn't contain `cmake` so while it doesn't break anything, it's also not exactly supported. If you add that in the `apt-install` line of the `Dockerfile`, all should be well (though perhaps also a good idea to add it to the github action to test it out during future PRs).

2022-01-24 15:53 UTC, mathematicalmichael commented
personal take: I suppose since `cmake` is intended to achieve platform and compiler independence, it sort of doesn't make sense to include it into the docker image since the point of the image is to ... also, make things "independent" in some sense (run on a common platform through use of virtualization). So I think it's best to leave it out of the image and assume the people reaching for `cmake` instead know what they're doing as far as compiling, whereas the `docker` image provides a bit more of a "standard entrypoint" for newcomers / those familiar with software in general but less with C specifically.

2022-02-08 20:02 UTC, merged

2024-01-03 12:11 UTC, NitishDragneel commented
I'm entirely new to this but i checked every file and understood what each does. can anyone tell me how to execute all these and make them into a single console program? I'm good at interface build so i can alter a few layouts and make it seem like a real game into fun but i need all ur help. pls text my mail nitesh220301@gmail.com if anyone knows how to work this out

2024-01-11 19:22 UTC, davidrmiller commented
Hi @NitishDragneel , If you follow the steps in the README, the result will be a console program. There's no GUI in this project, but there are forks of the project that include a graphical interface. If you encounter any problem following the README, let us know how far you got and what problem you encountered and we'll try to help.

2024-01-15 06:48 UTC, NitishDragneel commented
> Hi @NitishDragneel , If you follow the steps in the README, the result will be a console program. There's no GUI in this project, but there are forks of the project that include a graphical interface. If you encounter any problem following the README, let us know how far you got and what problem you encountered and we'll try to help.

Hey hii I'm very much confused because ubuntu is new to me.... Can i get your email id? Or wherever i can contact you personally pls? This is something im very much interested to learn

2024-01-16 05:38 UTC, davidrmiller commented
@NitishDragneel, I applaud your willingness to explore new territory.

I assume you're a Windows user. Since I rarely use Windows, it's best if we keep this discussion public where others can contribute their expertise.

Your first step is to set up an Ubuntu development environment on Windows. As I understand it, you have several options. One way is with WSL, the Windows Subsystem for Linux. Another is to set up an Ubuntu virtual machine with VirtualBox. Check out Issue #89 as it may have additional information on those options. Other options include setting up a dual-boot computer that boots Windows and Linux, or load Linux onto a spare computer and dedicate that computer for Linux development.

Once you are able to invoke a Linux terminal by whatever method, then you should be able to clone the biosim4 repository, install the dependencies mentioned in the README file, and execute make to generate an executable program.

If you get stuck along the way, feel free to open a new Issue with specific questions. Good luck!

2024-01-16 18:21 UTC, NitishDragneel commented
DEPRECATED: The legacy builder is deprecated and will be removed in a
future release.
            Install the buildx component to build images with BuildKit:
            https://docs.docker.com/go/buildx/

Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the
docker daemon running?


this is the first issue im facing when i try to build docker with "docker
build -t biosim4 ."

On Tue, Jan 16, 2024 at 11:09 AM David R. Miller ***@***.***>
wrote:

> @NitishDragneel <https://github.com/NitishDragneel>, I applaud your
> willingness to explore new territory.
>
> I assume you're a Windows user. Since I rarely use Windows, it's best if
> we keep this discussion public where others can contribute their expertise.
>
> Your first step is to set up an Ubuntu development environment on Windows.
> As I understand it, you have several options. One way is with WSL, the
> Windows Subsystem for Linux. Another is to set up an Ubuntu virtual machine
> with VirtualBox. Check out Issue #89
> <https://github.com/davidrmiller/biosim4/issues/89> as it may have
> additional information on those options. Other options include setting up a
> dual-boot computer that boots Windows and Linux, or load Linux onto a spare
> computer and dedicate that computer for Linux development.
>
> Once you are able to invoke a Linux terminal by whatever method, then you
> should be able to clone the biosim4 repository, install the dependencies
> mentioned in the README file, and execute make to generate an executable
> program.
>
> If you get stuck along the way, feel free to open a new Issue with
> specific questions. Good luck!
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/davidrmiller/biosim4/pull/41#issuecomment-1893101526>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/BDRSYX6RFKK3VBOOSZLMQGTYOYG73AVCNFSM5J4VOUQ2U5DIOJSWCZC7NNSXTN2JONZXKZKDN5WW2ZLOOQ5TCOBZGMYTAMJVGI3A>
> .
> You are receiving this because you were mentioned.Message ID:
> ***@***.***>
>

2024-01-16 20:00 UTC, davidrmiller commented
@NitishDragneel, since this discussion has shifted to docker, I opened Issue #97 about this. Let's continue this discussion there.